@QcOnLocation_HostAddress = http://localhost:5267

GET {{QcOnLocation_HostAddress}}/locations
Accept: application/json

###

POST {{QcOnLocation_HostAddress}}/location
Content-Type: application/json 

{
  
  "Name": "BD Check",
  "Description": "PLease god work",
  "LatLong": "37.7749 N-122.4194",
  "Tags": ["tag7", "tag8"]
}

###

DELETE {{QcOnLocation_HostAddress}}/location/2
Accept: application/json  


###

PUT {{QcOnLocation_HostAddress}}/location/1
Content-Type: application/json

{
  "Id": "1",
  "name":"Location 1701-f",
  "description":"Description Updated with put",
  "latLong":"37.7749 N-122.4194",
  "tags":["tag7","tag8"]
}
