@QcOnLocation_HostAddress = http://localhost:5267

GET {{QcOnLocation_HostAddress}}/locations
Accept: application/json

###

POST {{QcOnLocation_HostAddress}}/location
Content-Type: application/json 

{
  
  "Name": "Location 1701-f",
  "Description": "Description f",
  "LatLong": "37.7749 N-122.4194",
  "Tags": ["tag7", "tag8"]
}

###

DELETE {{QcOnLocation_HostAddress}}/location/4
Accept: application/json  


###

PUT {{QcOnLocation_HostAddress}}/location
Content-Type: application/json

{
  "Id": "4",
  "Name": "Updated Name",
  "Description": "Updated Description",
  "LatLong": "Updated 37.7749 N-122.4194",
  "Tags": ["Updated tag7", "Updated tag8"]
}
