@QcOnLocation_HostAddress = http://localhost:5267

GET {{QcOnLocation_HostAddress}}/locations
Accept: application/json

###

POST {{QcOnLocation_HostAddress}}/location
Content-Type: application/json 

{
  
  "Name": "My house",
  "Description": "It's a very fine house",
  "LatLong": "37.7749 N-122.4194",
  "Tags": ["tag7", "tag8"]
}

###

DELETE {{QcOnLocation_HostAddress}}/location/5
Accept: application/json  


###

PUT {{QcOnLocation_HostAddress}}/location/5
Content-Type: application/json

{
  "Id": "5",
  "name":"Your house",
  "description":"Runs house",
  "latLong":"37.7749 N-122.4194",
  "tags":["tag7","tag8"]
}
